(function(root){
  'use strict';
  var app, rows=[], signature='', loading=null, generation=0, owner=null, error='', dialog=null, returnFocus=null;
  var search='', year='', order='recent', trash=false, stateFilter='', noteDialog=null;
  var D=function(){return root.GrowellArchiveDomain;};
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  function icon(name){var paths={plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',book:'M12 5v15M3 4c3-1 6-1 9 1 3-2 6-2 9-1v15c-3-1-6-1-9 1-3-2-6-2-9-1Z'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>';}
  function cover(book,cls){var url=D().safeCoverUrl(book.coverUrl);return '<span class="archive-cover '+(cls||'')+'">'+(url?'<img src="'+esc(url)+'" alt="'+esc(book.title)+' 표지" loading="lazy" referrerpolicy="no-referrer">':'<span class="archive-cover-fallback">'+icon('book')+'<span>'+esc(book.title||'나의 책')+'</span></span>')+'</span>';}
  function stars(r){return '<span class="archive-stars" aria-label="'+(r?'5점 만점에 '+r+'점':'평가 전')+'">'+[1,2,3,4,5].map(function(n){return '<span'+(n<=r?' class="is-rated"':'')+' aria-hidden="true">★</span>';}).join('')+'</span>';}
  function period(b){return (b.startDate||'시작일 미기록')+' — '+(b.endDate||(b.status==='reading'?'읽는 중':'완독일 미기록'));}
  function stateName(b){return {unread:'읽기 전',reading:'읽는 중',completed:'완독'}[b.status];}
  function badge(b){return '<span class="archive-state archive-state-'+b.status+'">'+stateName(b)+'</span>';}
  function progressHtml(b){var p=D().progress(b);return '<span class="archive-progress"><span class="archive-progress-label"><span>'+p.currentPage+' / '+(p.totalPages||'—')+'쪽</span><strong>'+(p.percent===null?'전체 쪽수 미입력':p.percent+'%')+'</strong></span><span class="archive-progress-track"'+(p.percent===null?'':' role="progressbar" aria-label="읽은 비율" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+p.percent+'"')+'><span style="width:'+(p.percent||0)+'%"></span></span></span>';}
  function duration(seconds){var h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return (h?h+'시간 ':'')+(m?m+'분 ':'')+(!h&&!m?s+'초':'');}
  function dateTime(at){return new Date(at).toLocaleString('ko-KR',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
  async function latestRow(id){var entries=app.entries().filter(function(e){return e.id===id;});if(!entries.length)throw new Error('책을 다시 불러와 주세요.');return (await app.read(entries))[0];}
  async function persist(row,book,createId){var saved=await app.save(row,book,createId);if(saved){var index=rows.findIndex(function(r){return r.entry.id===saved.entry.id;});if(index>=0)rows[index]=saved;else rows.push(saved);}signature='';return saved;}
  function configure(adapter){app=adapter;}
  function reset(){generation++;rows=[];signature='';loading=null;owner=null;error='';search='';year='';trash=false;stateFilter='';if(root.GrowellArchiveTimer)root.GrowellArchiveTimer.reset();closeNote();close(false,true);}
  function ensure(){
    var session=app.session();if(!session)return;
    if(owner!==session.userId){reset();owner=session.userId;}
    if(app.status()!=='ready')return;
    var entries=app.entries().filter(function(e){return e.userId===owner&&D().isArchiveEntry(e);});
    var sig=entries.map(function(e){return e.id+':'+e.data;}).sort().join('|');
    if(sig===signature&&loading===null&&rows._loaded)return;
    if(loading===sig)return;
    var token=++generation,expected=owner;loading=sig;error='';
    app.read(entries).then(function(items){
      if(token!==generation||!app.session()||app.session().userId!==expected)return;
      rows=items;rows._loaded=true;signature=sig;loading=null;app.render();
    }).catch(function(){if(token!==generation)return;loading=null;error='아카이브를 불러오지 못했어요. 기존 기록은 안전하게 보관되어 있어요.';signature=sig;rows._loaded=true;app.render();});
  }
  function html(){
    if(!app.session())return '<section class="wrap archive-page"><div class="archive-empty">'+icon('book')+'<h1>나만의 독서 아카이브</h1><p>읽고 싶은 책과 독서 기록을 로그인한 나에게만 보이는 책장에 모아보세요.</p><a class="btn btn-primary" href="#/login">로그인하고 책장 열기</a></div></section>';
    ensure();
    return '<section class="wrap archive-page"><header class="archive-heading"><div><span class="archive-eyebrow">MY READING ARCHIVE</span><h1>읽고 남은 것들</h1><p>읽고 싶은 책부터, 오래 남을 기록까지.</p></div><button class="btn btn-primary" data-archive-add>'+icon('plus')+'<span>책 등록</span></button></header>'+
      '<div id="archive-content">'+contentHtml()+'</div><p class="archive-private-note">나의 책과 평가는 로그인한 나에게만 보여요.</p></section>';
  }
  function contentHtml(){
    if(app.status()!=='ready')return app.statusHtml();
    if(error)return '<div class="empty" role="alert">'+esc(error)+'<br><button class="btn btn-secondary" data-archive-retry>다시 불러오기</button></div>';
    if(!rows._loaded)return '<div class="empty" role="status">나의 책장을 펼치는 중이에요…</div>';
    var all=rows.filter(function(r){return !r.book.deleted;}),rated=all.filter(function(r){return r.book.rating>0;}),years=[...new Set(all.map(function(r){return r.book.endDate.slice(0,4);}).filter(Boolean))].sort().reverse();
    var visible=rows.filter(function(r){var b=r.book;return !!b.deleted===trash&&(!stateFilter||b.status===stateFilter)&&(!year||b.endDate.slice(0,4)===year)&&(!search||(b.title+' '+b.authors.join(' ')+' '+b.review).toLowerCase().includes(search.toLowerCase()));});
    visible.sort(function(a,b){return order==='rating'?(b.book.rating-a.book.rating||b.entry.createdAt-a.entry.createdAt):order==='title'?a.book.title.localeCompare(b.book.title,'ko'):(b.book.endDate||'').localeCompare(a.book.endDate||'')||b.entry.createdAt-a.entry.createdAt;});
    var stats='<div class="archive-stats"><span><strong>'+all.length+'</strong>권의 책</span><span><strong>'+(rated.length?(rated.reduce(function(s,r){return s+r.book.rating;},0)/rated.length).toFixed(1):'—')+'</strong>평균 별점</span><span><strong>'+all.filter(function(r){return r.book.review;}).length+'</strong>개의 감상</span></div>';
    var controls='<div class="archive-toolbar"><label class="archive-filter-search">'+icon('search')+'<input id="archive-filter" type="search" placeholder="제목, 저자, 감상 찾기" aria-label="내 책 검색" value="'+esc(search)+'"></label><div class="archive-filter-options"><select id="archive-year" aria-label="읽은 연도"><option value="">모든 연도</option>'+years.map(function(y){return '<option'+(year===y?' selected':'')+'>'+y+'</option>';}).join('')+'</select><select id="archive-sort" aria-label="책 정렬"><option value="recent"'+(order==='recent'?' selected':'')+'>최근 읽은 순</option><option value="rating"'+(order==='rating'?' selected':'')+'>별점 높은 순</option><option value="title"'+(order==='title'?' selected':'')+'>제목순</option></select><button type="button" class="archive-trash-toggle" data-archive-trash aria-pressed="'+trash+'">'+(trash?'책장으로':'휴지통')+'</button></div></div>';
    var grid=visible.length?'<div class="archive-grid">'+visible.map(function(r){var b=r.book;return '<button type="button" class="archive-book" data-archive-open="'+esc(r.entry.id)+'" aria-haspopup="dialog">'+cover(b)+'<span class="archive-book-title">'+esc(b.title)+'</span><span class="archive-author">'+esc(b.authors.join(' · ')||'저자 미기록')+'</span>'+badge(b)+progressHtml(b)+stars(b.rating)+'<span class="archive-date">'+esc(b.endDate?b.endDate.replace(/-/g,'.')+' 완독':b.startDate?b.startDate.replace(/-/g,'.')+' 시작':'독서 날짜 미기록')+'</span></button>';}).join('')+'</div>':'<div class="archive-empty">'+icon('book')+'<h2>'+(trash?'휴지통이 비어 있어요':all.length?'찾는 책이 없어요':'나만의 책장을 채워보세요')+'</h2><p>'+(all.length||trash?'검색어와 필터를 바꿔보세요.':'책을 찾아 담고, 읽은 시간과 마음에 남은 이유를 기록해요.')+'</p>'+(!all.length&&!trash?'<button class="btn btn-primary" data-archive-add>첫 번째 책 등록</button>':'')+'</div>';
    var tabs='<div class="archive-status-tabs" aria-label="독서 상태">'+[['','전체'],['unread','읽기 전'],['reading','읽는 중'],['completed','완독']].map(function(pair){return '<button type="button" data-archive-status="'+pair[0]+'" aria-pressed="'+(stateFilter===pair[0])+'">'+pair[1]+' <span>'+all.filter(function(r){return !pair[0]||r.book.status===pair[0];}).length+'</span></button>';}).join('')+'</div>';
    return stats+tabs+controls+grid;
  }
  function refresh(){var node=root.document.getElementById('archive-content');if(node){node.innerHTML=contentHtml();bindContent(node);}}
  function bindContent(node){
    node.querySelectorAll('[data-archive-add]').forEach(function(b){b.onclick=function(){open(null,b);};});
    node.querySelectorAll('[data-archive-open]').forEach(function(b){b.onclick=function(){open(b.dataset.archiveOpen,b);};});
    node.querySelectorAll('[data-archive-status]').forEach(function(b){b.onclick=function(){stateFilter=b.dataset.archiveStatus;refresh();};});
    var input=node.querySelector('#archive-filter');if(input)input.oninput=function(){var start=input.selectionStart;search=input.value;refresh();var n=root.document.getElementById('archive-filter');n.focus({preventScroll:true});try{n.setSelectionRange(start,start);}catch(e){}};
    var y=node.querySelector('#archive-year');if(y)y.onchange=function(){year=y.value;refresh();};
    var s=node.querySelector('#archive-sort');if(s)s.onchange=function(){order=s.value;refresh();};
    var t=node.querySelector('[data-archive-trash]');if(t)t.onclick=function(){trash=!trash;refresh();};
    var retry=node.querySelector('[data-archive-retry]');if(retry)retry.onclick=function(){signature='';rows._loaded=false;app.reload();};
    bindImages(node);
  }
  function bindImages(node){node.querySelectorAll('.archive-cover img').forEach(function(img){img.onerror=function(){var span=root.document.createElement('span');span.className='archive-cover-fallback';span.textContent=img.alt.replace(/ 표지$/,'');img.replaceWith(span);};});}
  function bind(){if(!app)return;if(owner&&(!app.session()||owner!==app.session().userId))reset();root.document.querySelectorAll('.archive-page,.archive-records').forEach(bindContent);}
  function canClose(){return !dialog||!dialog._dirty||root.confirm('작성 중인 내용이 있어요. 저장하지 않고 닫을까요?');}
  function close(restore,force){if(!dialog||(!force&&!canClose()))return;var node=dialog,target=returnFocus;dialog=null;returnFocus=null;if(node._searchAbort)node._searchAbort.abort();node.close();node.remove();if(root.GrowellPopupHistory)root.GrowellPopupHistory.closed('archive');if(restore!==false&&target&&target.isConnected)target.focus({preventScroll:true});}
  function shell(title){return '<header class="archive-dialog-head"><h2 id="archive-dialog-title">'+title+'</h2><button type="button" class="icon-btn" data-archive-close aria-label="아카이브 닫기">'+icon('close')+'</button></header><div class="archive-dialog-body"></div>';}
  function open(id,trigger){
    if(!app.session()||app.status()!=='ready')return;
    var row=id?rows.find(function(r){return r.entry.id===id;}):null;if(id&&!row)return;
    close(false,true);returnFocus=trigger;dialog=root.document.createElement('dialog');var node=dialog;node._createId='arc_'+root.crypto.randomUUID();
    node.className='archive-dialog';node.setAttribute('aria-labelledby','archive-dialog-title');node.innerHTML=shell(row?'나의 독서 기록':'책 등록');root.document.body.appendChild(node);
    node.querySelector('[data-archive-close]').onclick=function(){close();};node.addEventListener('cancel',function(e){e.preventDefault();close();});node.addEventListener('input',function(){node._dirty=true;});
    if(row)showDetail(node,row);else showForm(node,null,{});
    node.showModal();if(root.GrowellPopupHistory)root.GrowellPopupHistory.open('archive',{canClose:canClose,close:function(){if(dialog===node)close(true,true);}});
  }
  function showDetail(node,row){
    var b=row.book;node._dirty=false;
    node.querySelector('.archive-dialog-body').innerHTML='<div class="archive-detail-book">'+cover(b)+'<div><span class="archive-eyebrow">READ & REMEMBER</span><h3>'+esc(b.title)+'</h3><p>'+esc(b.authors.join(' · '))+'</p><p class="archive-detail-publisher">'+esc([b.publisher,b.publishedDate].filter(Boolean).join(' · '))+'</p>'+stars(b.rating)+'</div></div><div class="archive-period"><span>함께한 시간</span><strong>'+esc(period(b))+'</strong></div><section class="archive-reflection"><h3>이 별점을 남긴 이유</h3><p>'+esc(b.review||'아직 남긴 감상이 없어요.')+'</p></section>'+(b.description?'<details class="archive-description"><summary>책 소개</summary><p>'+esc(b.description)+'</p>'+(b.sourceUrl?'<a href="'+esc(b.sourceUrl)+'" target="_blank" rel="noopener noreferrer">도서 정보 출처 ↗</a>':'')+'</details>':'')+'<div class="archive-dialog-actions">'+(b.deleted?'<button class="btn btn-primary" data-archive-restore>책장으로 복원</button>':'<button class="btn btn-secondary" data-archive-remove>휴지통으로</button><button class="btn btn-primary" data-archive-edit>기록 수정</button>')+'</div><p class="archive-form-status" role="status"></p>';
    var body=node.querySelector('.archive-dialog-body'),periodNode=body.querySelector('.archive-period');
    periodNode.insertAdjacentHTML('beforebegin','<section class="archive-reading-summary">'+badge(b)+progressHtml(b)+'<p class="archive-time">총 읽은 시간 <strong>'+esc(duration(D().totalReadingSeconds(b)))+'</strong></p>'+(!b.deleted?'<div class="archive-reading-actions"><button class="btn btn-primary" data-archive-timer>'+(b.status==='completed'?'다시 읽기':'타이머로 읽기')+'</button><button class="btn btn-secondary" data-archive-note-add>노트 작성</button></div>':'')+'</section>');
    body.querySelector('.archive-dialog-actions').insertAdjacentHTML('beforebegin',historyHtml(b));
    if(!b.description&&b.sourceUrl)body.querySelector('.archive-dialog-actions').insertAdjacentHTML('beforebegin','<p><a href="'+esc(b.sourceUrl)+'" target="_blank" rel="noopener noreferrer">도서 정보 보기 ↗</a></p>');
    var edit=node.querySelector('[data-archive-edit]');if(edit)edit.onclick=function(){showForm(node,row,b);};
    var timer=node.querySelector('[data-archive-timer]');if(timer)timer.onclick=function(){openTimer(node,row);};
    var addNote=node.querySelector('[data-archive-note-add]');if(addNote)addNote.onclick=function(){openNote(row,null,function(){updateDetail(node,row.entry.id);});};
    body.querySelectorAll('[data-archive-note-edit]').forEach(function(button){button.onclick=function(){openNote(row,button.dataset.archiveNoteEdit,function(){updateDetail(node,row.entry.id);});};});
    body.querySelectorAll('[data-archive-note-delete]').forEach(function(button){button.onclick=async function(){if(!root.confirm('이 노트를 삭제할까요?'))return;button.disabled=true;try{var latest=await latestRow(row.entry.id);await persist(latest,D().removeNote(latest.book,button.dataset.archiveNoteDelete,Date.now()));await updateDetail(node,row.entry.id);app.render();}catch(e){node.querySelector('.archive-form-status').textContent=e.message;button.disabled=false;}};});
    var remove=node.querySelector('[data-archive-remove]'),restore=node.querySelector('[data-archive-restore]');
    function move(deleted,button){button.disabled=true;app.save(row,Object.assign({},b,{deleted:deleted})).then(function(){if(dialog===node){close(true,true);app.render();}app.toast(deleted?'휴지통으로 옮겼어요. 언제든 복원할 수 있어요.':'책장으로 복원했어요.');}).catch(function(e){if(dialog!==node)return;button.disabled=false;node.querySelector('.archive-form-status').textContent=e.message;});}
    if(remove)remove.onclick=function(){move(true,remove);};if(restore)restore.onclick=function(){move(false,restore);};bindImages(node);
  }
  function historyHtml(b){return '<section class="archive-notes"><h3>나의 기록</h3>'+b.notes.filter(function(n){return !n.deleted;}).slice().sort(function(a,b){return b.createdAt-a.createdAt;}).map(function(n){return '<article><span class="archive-note-date">'+esc(dateTime(n.createdAt))+'</span><p>'+esc(n.text)+'</p>'+(!b.deleted?'<div><button type="button" data-archive-note-edit="'+n.id+'">수정</button><button type="button" data-archive-note-delete="'+n.id+'">삭제</button></div>':'')+'</article>';}).join('')+(!b.notes.some(function(n){return !n.deleted;})?'<p class="archive-form-hint">기억하고 싶은 문장과 생각을 남겨보세요.</p>':'')+'</section><details class="archive-sessions"><summary>읽은 기록 보기 ('+b.readingSessions.length+')</summary>'+b.readingSessions.slice().sort(function(a,b){return b.createdAt-a.createdAt;}).map(function(s){return '<div><span><small>'+esc(dateTime(s.createdAt))+'</small><strong>'+s.startPage+' → '+s.endPage+'쪽</strong></span><span>'+esc(duration(s.seconds))+'</span></div>';}).join('')+'</details>';}
  async function updateDetail(node,id){try{var latest=await latestRow(id);if(dialog===node)showDetail(node,latest);}catch(e){if(dialog===node)node.querySelector('.archive-form-status').textContent=e.message;}}
  function openTimer(node,row){var b=row.book;root.GrowellArchiveTimer.open({book:{id:row.entry.id,title:b.title,authors:b.authors,coverUrl:b.coverUrl,pageCount:b.totalPages,currentPage:b.status==='completed'?0:b.currentPage},ownerId:app.session().userId,adapter:{beforeStart:function(ownerId){return app.beforeTimerStart?app.beforeTimerStart(ownerId):true;},getOwnerId:function(){return app.session()&&app.session().userId;},saveSession:async function(id,session,options){var latest=await latestRow(id);if(latest.book.deleted)throw new Error('휴지통의 책은 복원한 뒤 기록해주세요.');var next=D().addReadingSession(latest.book,session,options);var day=new Date(session.createdAt).toLocaleDateString('sv-SE');if(!next.startDate)next.startDate=day;if(next.status==='completed'&&!next.endDate)next.endDate=day;await persist(latest,next);},openNote:function(book,options){latestRow(book.id).then(function(latest){openNote(latest,null,options&&options.onClose);}).catch(function(e){app.toast(e.message);if(options&&options.onClose)options.onClose();});},onClose:function(){updateDetail(node,row.entry.id);},onSaved:function(){updateDetail(node,row.entry.id);app.render();}}});}
  function closeNote(){if(!noteDialog)return;var n=noteDialog;noteDialog=null;n.close();n.remove();if(root.GrowellPopupHistory)root.GrowellPopupHistory.closed('archive-note');if(n._onClose)n._onClose();}
  function openNote(row,id,onClose){
    closeNote();var old=id?row.book.notes.find(function(n){return n.id===id;}):null;var noteId=old?old.id:'note_'+root.crypto.randomUUID(),created=old?old.createdAt:Date.now();
    var n=root.document.createElement('dialog');noteDialog=n;n._onClose=onClose;n.className='archive-dialog archive-note-dialog';n.setAttribute('aria-label','독서 노트');n.innerHTML='<header class="archive-dialog-head"><h2>'+esc(row.book.title)+'</h2><button type="button" class="icon-btn" data-note-close aria-label="노트 닫기">'+icon('close')+'</button></header><form id="archive-note-form" class="archive-dialog-body"><label class="archive-field">나의 기록<textarea name="text" rows="7" maxlength="10000" required placeholder="책 속 문장과 나의 생각을 남겨주세요.">'+esc(old?old.text:'')+'</textarea></label><p class="archive-form-status" role="status"></p><button type="submit" class="btn btn-primary" data-archive-note-save>노트 저장</button></form>';root.document.body.appendChild(n);
    function canCloseNote(){return !n._busy&&(!n._dirty||root.confirm('작성 중인 노트를 저장하지 않고 닫을까요?'));}
    n.querySelector('[data-note-close]').onclick=function(){if(canCloseNote())closeNote();};n.addEventListener('cancel',function(e){e.preventDefault();if(canCloseNote())closeNote();});n.addEventListener('input',function(){n._dirty=true;});
    n.querySelector('form').onsubmit=async function(e){e.preventDefault();var form=e.currentTarget,button=form.querySelector('button');if(button.disabled)return;button.disabled=true;n._busy=true;try{var latest=await latestRow(row.entry.id);if(latest.book.deleted)throw new Error('책을 복원한 뒤 노트를 작성해주세요.');if(old){var current=latest.book.notes.find(function(item){return item.id===id;});if(JSON.stringify(current)!==JSON.stringify(old))throw new Error('다른 곳에서 수정된 노트예요. 다시 열어주세요.');}var next=D().upsertNote(latest.book,{id:noteId,text:form.elements.text.value,createdAt:created,updatedAt:old?Date.now():null});await persist(latest,next);if(noteDialog===n){n._dirty=false;closeNote();app.render();}}catch(err){if(noteDialog===n)form.querySelector('.archive-form-status').textContent=err.message;}finally{n._busy=false;button.disabled=false;}};
    n.showModal();if(root.GrowellPopupHistory)root.GrowellPopupHistory.open('archive-note',{canClose:canCloseNote,close:closeNote});
  }
  function recordsHtml(){
    if(!app||!app.session())return '';ensure();if(app.status()!=='ready'||!rows._loaded||error)return '';
    var records=[];rows.filter(function(r){return !r.book.deleted;}).forEach(function(r){r.book.notes.filter(function(n){return !n.deleted;}).forEach(function(n){records.push({row:r,at:n.createdAt,text:n.text,type:'독서 노트'});});r.book.readingSessions.forEach(function(s){records.push({row:r,at:s.createdAt,text:s.startPage+' → '+s.endPage+'쪽 읽음',type:'읽은 기록'});});if(r.book.review)records.push({row:r,at:r.entry.updatedAt||r.entry.createdAt,text:r.book.review,type:'나의 감상'});});records.sort(function(a,b){return b.at-a.at;});
    return '<section class="archive-records"><header><h3>아카이브 기록 <span>'+records.length+'</span></h3><a href="#/archive">책장 보기 →</a></header>'+(records.length?'<div>'+records.slice(0,30).map(function(item){return '<button type="button" data-archive-open="'+esc(item.row.entry.id)+'">'+cover(item.row.book)+'<span><small>'+esc(item.type+' · '+dateTime(item.at))+'</small><strong>'+esc(item.row.book.title)+'</strong><span class="archive-record-excerpt">'+esc(item.text)+'</span></span></button>';}).join('')+'</div>':'<p>아카이브에서 남긴 노트와 읽은 기록을 여기에서도 볼 수 있어요.</p>')+'</section>';
  }
  function field(label,key,value,type){return '<label class="archive-field">'+label+'<input name="'+key+'" type="'+(type||'text')+'" value="'+esc(value||'')+'"'+(key==='title'?' required maxlength="300"':'')+'></label>';}
  function showForm(node,row,initial){
    var b=Object.assign({authors:[],rating:0,status:'unread',currentPage:0},initial),selected=b;
    node.querySelector('.archive-dialog-body').innerHTML=(row?'':'<section class="archive-book-search"><h3>어떤 책을 담을까요?</h3><form id="archive-search-form"><label class="archive-filter-search">'+icon('search')+'<input name="query" aria-label="등록할 책 검색" placeholder="책 제목 · 저자 · ISBN" minlength="2" maxlength="120" required></label><button class="btn btn-secondary" type="submit">검색</button></form><p class="archive-search-note" role="status">검색한 책을 선택하면 표지와 기본 정보가 채워져요. 아래에 직접 입력해도 좋아요.</p><div class="archive-search-results"></div></section>')+
      '<form id="archive-form"><div class="archive-form-book"><div><div id="archive-cover-preview">'+cover(b)+'</div><label class="archive-upload">표지 사진 선택<input type="file" accept="image/jpeg,image/png,image/webp" name="coverFile"></label></div><div>'+field('책 제목','title',b.title)+field('저자','authors',(b.authors||[]).join(', '))+field('출판사','publisher',b.publisher)+'</div></div><div class="archive-date-fields">'+field('읽기 시작한 날','startDate',b.startDate,'date')+field('다 읽은 날','endDate',b.endDate,'date')+'</div><p class="archive-form-hint">정확한 날짜가 기억나지 않으면 비워두어도 좋아요.</p><fieldset class="archive-rating"><legend>나의 별점</legend><div>'+[1,2,3,4,5].map(function(n){return '<label title="'+n+'점"><input type="radio" name="rating" value="'+n+'"'+(b.rating===n?' checked':'')+'><span aria-hidden="true">★</span><span class="sr-only">'+n+'점</span></label>';}).join('')+'<button type="button" data-clear-rating>초기화</button></div></fieldset><label class="archive-field">이 별점을 남긴 이유<textarea name="review" rows="4" maxlength="10000" placeholder="좋았던 점, 아쉬웠던 점, 오래 기억하고 싶은 생각을 남겨주세요.">'+esc(b.review||'')+'</textarea></label><details class="archive-description"><summary>책 소개 수정</summary><label class="archive-field"><span class="sr-only">책 소개</span><textarea name="description" rows="4" maxlength="16000">'+esc(b.description||'')+'</textarea></label></details><p class="archive-form-status" role="status"></p><div class="archive-dialog-actions">'+(row?'<button type="button" class="btn btn-secondary" data-archive-cancel-edit>돌아가기</button>':'')+'<button type="submit" class="btn btn-primary">'+(row?'수정 저장':'책장에 담기')+'</button></div></form>';
    var form=node.querySelector('#archive-form'),status=form.querySelector('.archive-form-status');
    form.querySelector('.archive-date-fields').insertAdjacentHTML('beforebegin','<fieldset class="archive-status-fields"><legend>독서 상태</legend><div>'+[['unread','읽기 전'],['reading','읽는 중'],['completed','완독']].map(function(pair){return '<label><input type="radio" name="status" value="'+pair[0]+'"'+(b.status===pair[0]?' checked':'')+'>'+pair[1]+'</label>';}).join('')+'</div></fieldset><div class="archive-page-fields">'+field('현재 읽은 쪽수','currentPage',String(b.currentPage||0),'number')+field('전체 쪽수','totalPages',b.totalPages||b.pageCount||'','number')+'</div>');
    form.elements.currentPage.min='0';form.elements.currentPage.max='100000';form.elements.totalPages.min='1';form.elements.totalPages.max='100000';
    function stateChanged(){var value=new FormData(form).get('status');form.elements.currentPage.disabled=value!=='reading';if(value==='unread')form.elements.currentPage.value='0';if(value==='completed'&&form.elements.totalPages.value)form.elements.currentPage.value=form.elements.totalPages.value;form.elements.endDate.disabled=value!=='completed';}
    form.querySelectorAll('[name="status"]').forEach(function(radio){radio.onchange=stateChanged;});form.elements.totalPages.oninput=stateChanged;stateChanged();
    function ratingPaint(){var value=Number(new FormData(form).get('rating')||0);form.querySelectorAll('.archive-rating label').forEach(function(label){label.classList.toggle('is-rated',Number(label.querySelector('input').value)<=value);});}ratingPaint();
    form.querySelectorAll('[name="rating"]').forEach(function(r){r.onchange=ratingPaint;});form.querySelector('[data-clear-rating]').onclick=function(){form.querySelectorAll('[name="rating"]').forEach(function(r){r.checked=false;});node._dirty=true;ratingPaint();};
    var cancel=form.querySelector('[data-archive-cancel-edit]');if(cancel)cancel.onclick=function(){if(canClose())showDetail(node,row);};
    form.elements.coverFile.onchange=async function(){var file=form.elements.coverFile.files[0];if(!file)return;var version=(node._coverVersion||0)+1;node._coverVersion=version;node._coverLoading=true;try{var result=await readCover(file);if(dialog!==node||node._coverVersion!==version)return;selected.coverUrl=result;node.querySelector('#archive-cover-preview').innerHTML=cover(Object.assign({},selected,{title:form.elements.title.value}));status.textContent='';}catch(e){if(dialog===node&&node._coverVersion===version)status.textContent=e.message;}finally{if(node._coverVersion===version)node._coverLoading=false;}};
    form.onsubmit=async function(event){event.preventDefault();var button=form.querySelector('[type="submit"]');if(button.disabled)return;if(node._coverLoading){status.textContent='표지 사진을 준비하고 있어요. 잠시 후 저장해주세요.';return;}button.disabled=true;status.textContent='저장 중…';var saveOwner=app.session()&&app.session().userId;try{var data=new FormData(form),book=Object.assign({},selected,{title:data.get('title'),authors:String(data.get('authors')||'').split(',').map(function(a){return a.trim();}).filter(Boolean),publisher:data.get('publisher'),startDate:data.get('startDate'),endDate:data.get('endDate'),rating:Number(data.get('rating')||0),review:data.get('review'),description:data.get('description'),status:data.get('status'),currentPage:Number(form.elements.currentPage.value||0),totalPages:data.get('totalPages')||null});D().prepare(book);await persist(row,book,node._createId);if(dialog===node){close(true,true);app.render();}if(app.session()&&app.session().userId===saveOwner)app.toast('나의 책장에 저장했어요.');}catch(e){if(dialog===node)status.textContent=e.message||'저장하지 못했어요. 다시 시도해주세요.';}finally{button.disabled=false;}};
    var searchForm=node.querySelector('#archive-search-form');if(searchForm)searchForm.onsubmit=async function(event){
      event.preventDefault();var query=searchForm.elements.query.value.trim();if(query.length<2)return;
      var note=node.querySelector('.archive-search-note'),results=node.querySelector('.archive-search-results');if(node._searchAbort)node._searchAbort.abort();var control=new AbortController();node._searchAbort=control;note.textContent='책을 찾는 중이에요…';results.innerHTML='';
      var local=app.catalog().filter(function(book){return (book.title+' '+book.authors.join(' ')).toLowerCase().includes(query.toLowerCase());});
      try{var response=await fetch('/api/book-search?q='+encodeURIComponent(query),{signal:control.signal});var remote=await response.json();if(dialog!==node||node._searchAbort!==control)return;var found=local.concat((remote.items||[]).map(function(item){return Object.assign({},item,{coverUrl:item.thumbnail});}));showResults(found,remote.error);}catch(e){if(e.name==='AbortError')return;if(dialog===node&&node._searchAbort===control)showResults(local,'검색 연결이 원활하지 않아요. 직접 등록할 수 있어요.');}
      function showResults(found,message){note.textContent=found.length?'등록할 책을 선택해주세요.':message||'검색 결과가 없어요. 제목이나 ISBN을 바꾸거나 아래에서 직접 등록해주세요.';results.innerHTML=found.map(function(book,i){return '<button type="button" data-search-result="'+i+'">'+cover(book)+'<span><strong>'+esc(book.title)+'</strong><small>'+esc(book.authors.join(' · '))+'</small><small>'+esc(book.publisher||'')+'</small></span></button>';}).join('');results.querySelectorAll('[data-search-result]').forEach(function(button){button.onclick=function(){var item=found[Number(button.dataset.searchResult)];selected=Object.assign({},item,{rating:0,deleted:false,status:'unread'});form.elements.totalPages.value=item.pageCount||'';stateChanged();form.elements.title.value=item.title;form.elements.authors.value=item.authors.join(', ');form.elements.publisher.value=item.publisher||'';form.elements.description.value=item.description||'';node.querySelector('#archive-cover-preview').innerHTML=cover(selected);node._dirty=true;results.innerHTML='';note.textContent='책 정보를 가져왔어요. 읽은 기간과 나의 평가를 남겨주세요.';form.elements.startDate.focus({preventScroll:true});};});bindImages(results);}
    };
    bindImages(node);
  }
  function readCover(file){return new Promise(function(resolve,reject){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>5*1024*1024){reject(new Error('5MB 이하의 JPG, PNG, WebP 사진을 선택해주세요.'));return;}var url=URL.createObjectURL(file),img=new Image();img.onload=function(){try{var scale=Math.min(1,600/Math.max(img.width,img.height)),canvas=root.document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));var ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',0.82));}catch(e){reject(new Error('사진을 읽지 못했어요. 다른 사진을 선택해주세요.'));}finally{URL.revokeObjectURL(url);}};img.onerror=function(){URL.revokeObjectURL(url);reject(new Error('사진을 읽지 못했어요.'));};img.src=url;});}
  root.addEventListener('hashchange',function(){closeNote();close(false,true);});
  root.GrowellArchive={configure:configure,html:html,recordsHtml:recordsHtml,bind:bind,reset:reset};
})(window);
