(function(root){
  'use strict';
  var app, rows=[], signature='', loading=null, generation=0, owner=null, error='', dialog=null, returnFocus=null;
  var search='', year='', order='recent', trash=false, stateFilter='', genreFilter='', noteFilter='', noteBookFilter='', noteDialog=null;
  var THEMES={emotion:'감정',thought:'생각',body:'신체',action:'행동'};
  var D=function(){return root.GrowellArchiveDomain;};
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  function icon(name){var paths={plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',book:'M12 5v15M3 4c3-1 6-1 9 1 3-2 6-2 9-1v15c-3-1-6-1-9 1-3-2-6-2-9-1Z'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>';}
  function cover(book,cls){var url=D().safeCoverUrl(book.coverUrl);return '<span class="archive-cover '+(cls||'')+'">'+(url?'<img src="'+esc(url)+'" alt="'+esc(book.title)+' 표지" loading="lazy" referrerpolicy="no-referrer">':'<span class="archive-cover-fallback">'+icon('book')+'<span>'+esc(book.title||'나의 책')+'</span></span>')+'</span>';}
  function sourceHref(book){
    try{var url=new URL(book.sourceUrl);if(url.protocol!=='https:'||url.username||url.password)return '';if(book.source==='yes24'){var id=url.pathname.match(/^\/(?:Product\/Goods|goods)\/(\d+)\/?$/i);return /^(?:www\.|m\.)?yes24\.com$/i.test(url.hostname)&&id?'https://www.yes24.com/Product/Goods/'+id[1]:'';}return url.href;}catch(e){return '';}
  }
  function sourceHtml(book){var href=sourceHref(book);if(book.source==='yes24')return '<span class="archive-source">도서 정보: '+(href?'<a href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">YES24 ↗</a>':'YES24')+'</span>';return '';}
  function stars(r){return '<span class="archive-stars" aria-label="'+(r?'5점 만점에 '+r+'점':'평가 전')+'">'+[1,2,3,4,5].map(function(n){return '<span'+(n<=r?' class="is-rated"':'')+' aria-hidden="true">★</span>';}).join('')+'</span>';}
  function period(b){return (b.startDate||'시작일 미기록')+' — '+(b.endDate||(b.status==='reading'?'읽는 중':'완독일 미기록'));}
  function stateName(b){return {unread:'읽기 전',reading:'읽는 중',completed:'완독'}[b.status];}
  function badge(b){return '<span class="archive-state archive-state-'+b.status+'">'+stateName(b)+'</span>';}
  function progressHtml(b){var p=D().progress(b);return '<span class="archive-progress"><span class="archive-progress-label"><span>'+p.currentPage+' / '+(p.totalPages||'—')+'쪽</span><strong>'+(p.percent===null?'전체 쪽수 미입력':p.percent+'%')+'</strong></span><span class="archive-progress-track"'+(p.percent===null?'':' role="progressbar" aria-label="읽은 비율" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+p.percent+'"')+'><span style="width:'+(p.percent||0)+'%"></span></span></span>';}
  function duration(seconds){var h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return (h?h+'시간 ':'')+(m?m+'분 ':'')+(!h&&!m?s+'초':'');}
  function dateTime(at){return new Date(at).toLocaleString('ko-KR',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
  async function latestRow(id){var expected=app.session()&&app.session().userId;if(!expected)throw new Error('로그인 후 다시 열어주세요.');var entries=app.entries().filter(function(e){return e.userId===expected&&D().isArchiveEntry(e);});var fresh=(await app.read(entries)).find(function(row){return row.entry.id===id&&row.entry.userId===expected;});if(!app.session()||app.session().userId!==expected)throw new Error('로그인한 계정이 바뀌었어요. 다시 열어주세요.');if(!fresh)throw new Error('책을 다시 불러와 주세요.');return fresh;}
  async function persist(row,book,createId){var saved=await app.save(row,book,createId);if(saved){var index=rows.findIndex(function(r){return r.entry.id===saved.entry.id;});if(index>=0)rows[index]=saved;else rows.push(saved);}signature='';return saved;}
  function configure(adapter){app=adapter;}
  function reset(){generation++;rows=[];signature='';loading=null;owner=null;error='';search='';year='';trash=false;stateFilter='';genreFilter='';noteFilter='';noteBookFilter='';if(root.GrowellArchiveTimer)root.GrowellArchiveTimer.reset();closeNote();close(false,true);}
  function ensure(){
    var session=app.session();if(!session)return;
    if(owner!==session.userId){reset();owner=session.userId;}
    if(app.status()!=='ready')return;
    var entries=app.entries().filter(function(e){return e.userId===owner&&D().isArchiveEntry(e);});
    var sig=entries.map(function(e){return e.id+':'+e.data;}).sort().join('|')+(app.linkedSignature?'|'+app.linkedSignature():'');
    if(sig===signature&&loading===null&&rows._loaded)return;
    if(loading===sig)return;
    var token=++generation,expected=owner;loading=sig;error='';
    app.read(entries).then(function(items){
      if(token!==generation||!app.session()||app.session().userId!==expected)return;
      rows=items.filter(function(row){return row.entry.userId===expected;});rows._loaded=true;signature=sig;loading=null;app.render();
    }).catch(function(){if(token!==generation)return;loading=null;error='아카이브를 불러오지 못했어요. 기존 기록은 안전하게 보관되어 있어요.';signature=sig;rows._loaded=true;app.render();});
  }
  function html(){
    if(!app.session())return '<section class="wrap archive-page"><div class="archive-empty">'+icon('book')+'<h1>나만의 독서 아카이브</h1><p>읽고 싶은 책과 독서 기록을 로그인한 나에게만 보이는 책장에 모아보세요.</p><a class="btn btn-primary" href="#/login">로그인하고 책장 열기</a></div></section>';
    ensure();
    return '<section class="wrap archive-page"><header class="archive-heading"><div><span class="archive-eyebrow">MY READING ARCHIVE</span><h1>읽고 남은 것들</h1><p>읽고 싶은 책부터, 오래 남을 기록까지.</p></div><button class="btn btn-primary" data-archive-add>'+icon('plus')+'<span>책 등록</span></button></header>'+
      '<div id="archive-content">'+contentHtml()+'</div><p class="archive-private-note">나의 책과 평가는 로그인한 나에게만 보여요.</p></section>';
  }
  function contentHtml(){
    if(app.status()!=='ready')return app.statusHtml();
    if(error)return '<div class="empty" role="alert">'+esc(error)+'<br><button class="btn btn-secondary" data-archive-retry>다시 불러오기</button></div>';
    if(!rows._loaded)return '<div class="empty" role="status">나의 책장을 펼치는 중이에요…</div>';
    var all=rows.filter(function(r){return !r.book.deleted;}),rated=all.filter(function(r){return r.book.rating>0;}),years=[...new Set(all.map(function(r){return r.book.endDate.slice(0,4);}).filter(Boolean))].sort().reverse();
    var genres=registeredGenres(all);if(genreFilter&&genres.indexOf(genreFilter)<0)genreFilter='';
    var visible=rows.filter(function(r){var b=r.book;return !!b.deleted===trash&&(!genreFilter||(b.genres||[]).indexOf(genreFilter)>=0)&&(!stateFilter||b.status===stateFilter)&&(!year||b.endDate.slice(0,4)===year)&&(!search||(b.title+' '+b.authors.join(' ')+' '+b.review).toLowerCase().includes(search.toLowerCase()));});
    visible.sort(function(a,b){return order==='rating'?(b.book.rating-a.book.rating||b.entry.createdAt-a.entry.createdAt):order==='title'?a.book.title.localeCompare(b.book.title,'ko'):(b.book.endDate||'').localeCompare(a.book.endDate||'')||b.entry.createdAt-a.entry.createdAt;});
    var stats='<div class="archive-stats"><span><strong>'+all.length+'</strong>권의 책</span><span><strong>'+(rated.length?(rated.reduce(function(s,r){return s+r.book.rating;},0)/rated.length).toFixed(1):'—')+'</strong>평균 별점</span><span><strong>'+all.filter(function(r){return r.book.review;}).length+'</strong>개의 감상</span></div>';
    var controls='<div class="archive-toolbar"><label class="archive-filter-search">'+icon('search')+'<input id="archive-filter" type="search" placeholder="제목, 저자, 감상 찾기" aria-label="내 책 검색" value="'+esc(search)+'"></label><div class="archive-filter-options"><select id="archive-year" aria-label="읽은 연도"><option value="">모든 연도</option>'+years.map(function(y){return '<option'+(year===y?' selected':'')+'>'+y+'</option>';}).join('')+'</select><select id="archive-sort" aria-label="책 정렬"><option value="recent"'+(order==='recent'?' selected':'')+'>최근 읽은 순</option><option value="rating"'+(order==='rating'?' selected':'')+'>별점 높은 순</option><option value="title"'+(order==='title'?' selected':'')+'>제목순</option></select><button type="button" class="archive-trash-toggle" data-archive-trash aria-pressed="'+trash+'">'+(trash?'책장으로':'휴지통')+'</button></div></div>';
    var grid=visible.length?'<div class="archive-grid">'+visible.map(function(r){var b=r.book;return '<article class="archive-book-entry"><button type="button" class="archive-book" data-archive-open="'+esc(r.entry.id)+'" aria-haspopup="dialog">'+cover(b)+'<span class="archive-book-title">'+esc(b.title)+'</span><span class="archive-author">'+esc(b.authors.join(' · ')||'저자 미기록')+'</span>'+((b.genres||[]).length?'<span class="archive-book-genre">'+esc(b.genres.join(' · '))+'</span>':'')+badge(b)+progressHtml(b)+stars(b.rating)+'<span class="archive-date">'+esc(b.endDate?b.endDate.replace(/-/g,'.')+' 완독':b.startDate?b.startDate.replace(/-/g,'.')+' 시작':'독서 날짜 미기록')+'</span></button>'+sourceHtml(b)+'</article>';}).join('')+'</div>':'<div class="archive-empty">'+icon('book')+'<h2>'+(trash?'휴지통이 비어 있어요':all.length?'찾는 책이 없어요':'나만의 책장을 채워보세요')+'</h2><p>'+(all.length||trash?'검색어와 필터를 바꿔보세요.':'책을 찾아 담고, 읽은 시간과 마음에 남은 이유를 기록해요.')+'</p>'+(!all.length&&!trash?'<button class="btn btn-primary" data-archive-add>첫 번째 책 등록</button>':'')+'</div>';
    var tabs='<div class="archive-status-tabs" aria-label="독서 상태">'+[['','전체'],['unread','읽기 전'],['reading','읽는 중'],['completed','완독']].map(function(pair){return '<button type="button" data-archive-status="'+pair[0]+'" aria-pressed="'+(stateFilter===pair[0])+'">'+pair[1]+' <span>'+all.filter(function(r){return !pair[0]||r.book.status===pair[0];}).length+'</span></button>';}).join('')+'</div>';
    var genreTabs=genres.length?'<div class="archive-genre-tabs" aria-label="책 장르"><button type="button" data-archive-genre="" aria-pressed="'+!genreFilter+'">전체 장르</button>'+genres.map(function(genre){return '<button type="button" data-archive-genre="'+esc(genre)+'" aria-pressed="'+(genreFilter===genre)+'">'+esc(genre)+'</button>';}).join('')+'</div>':'';
    return notesShelfHtml(all)+ '<section class="archive-bookshelf"><h2>나의 책장</h2>'+stats+tabs+genreTabs+controls+grid+'</section>';
  }
  function refresh(){var node=root.document.getElementById('archive-content');if(node){node.innerHTML=contentHtml();bindContent(node);}}
  function bindContent(node){
    node.querySelectorAll('[data-archive-add]').forEach(function(b){b.onclick=function(){open(null,b);};});
    node.querySelectorAll('[data-archive-open]').forEach(function(b){b.onclick=function(){open(b.dataset.archiveOpen,b);};});
    node.querySelectorAll('[data-archive-status]').forEach(function(b){b.onclick=function(){stateFilter=b.dataset.archiveStatus;refresh();};});
    node.querySelectorAll('[data-archive-genre]').forEach(function(b){b.onclick=function(){genreFilter=b.dataset.archiveGenre;refresh();};});
    node.querySelectorAll('[data-note-filter]').forEach(function(b){b.onclick=function(){noteFilter=b.dataset.noteFilter;refresh();};});
    var noteBooks=node.querySelector('[data-note-book-filter]');if(noteBooks)noteBooks.onchange=function(){noteBookFilter=noteBooks.value;refresh();};
    node.querySelectorAll('[data-archive-read-note]').forEach(function(button){button.onclick=function(){var row=rows.find(function(r){return r.entry.id===button.dataset.archiveNoteBook;});if(row)openNote(row,button.dataset.archiveReadNote,function(){app.render();},true,button);};});
    node.querySelectorAll('[data-shared-read-note]').forEach(function(button){button.onclick=function(){if(!app.openSharedNote)return;var expected=app.session()&&app.session().userId,item=sharedNoteRecords().find(function(record){return record.sharedId===button.dataset.sharedReadNote&&record.sharedBookId===button.dataset.sharedNoteBook;});if(!expected||!item)return;try{var result=app.openSharedNote(item.sharedId,item.sharedBookId);if(result&&result.catch)result.catch(function(err){if(app.session()&&app.session().userId===expected)app.toast(err.message||'기록을 다시 열어주세요.');});}catch(err){app.toast(err.message||'기록을 다시 열어주세요.');}};});
    var noteAdd=node.querySelector('[data-archive-note-selected-add]');if(noteAdd)noteAdd.onclick=function(){var row=rows.find(function(r){return r.entry.id===noteBookFilter;});if(row)openNote(row,null,function(){app.render();},false,noteAdd);};
    var input=node.querySelector('#archive-filter');if(input)input.oninput=function(){var start=input.selectionStart;search=input.value;refresh();var n=root.document.getElementById('archive-filter');n.focus({preventScroll:true});try{n.setSelectionRange(start,start);}catch(e){}};
    var y=node.querySelector('#archive-year');if(y)y.onchange=function(){year=y.value;refresh();};
    var s=node.querySelector('#archive-sort');if(s)s.onchange=function(){order=s.value;refresh();};
    var t=node.querySelector('[data-archive-trash]');if(t)t.onclick=function(){trash=!trash;refresh();};
    var retry=node.querySelector('[data-archive-retry]');if(retry)retry.onclick=function(){signature='';rows._loaded=false;app.reload();};
    bindImages(node);
  }
  function bindImages(node){node.querySelectorAll('.archive-cover img').forEach(function(img){img.onerror=function(){var span=root.document.createElement('span');span.className='archive-cover-fallback';span.textContent=img.alt.replace(/ 표지$/,'');img.replaceWith(span);};});}
  function bind(){if(!app)return;if(owner&&(!app.session()||owner!==app.session().userId))reset();root.document.querySelectorAll('.archive-page,.archive-records').forEach(bindContent);}
  function canClose(){return !dialog||!dialog._dirty||root.confirm('작성 중인 내용이 있어요. 저장하지 않고 닫을까요?');}
  function close(restore,force){if(!dialog||(!force&&!canClose()))return;var node=dialog,target=returnFocus;dialog=null;returnFocus=null;if(node._searchAbort)node._searchAbort.abort();if(node._genreAbort)node._genreAbort.abort();node.close();node.remove();if(root.GrowellPopupHistory)root.GrowellPopupHistory.closed('archive');if(restore!==false&&target&&target.isConnected)target.focus({preventScroll:true});}
  function shell(title){return '<header class="archive-dialog-head"><h2 id="archive-dialog-title">'+title+'</h2><button type="button" class="icon-btn" data-archive-close aria-label="아카이브 닫기">'+icon('close')+'</button></header><div class="archive-dialog-body"></div>';}
  function open(id,trigger){
    if(!app.session()||app.status()!=='ready')return;
    var row=id?rows.find(function(r){return r.entry.id===id;}):null;if(id&&!row)return;
    close(false,true);returnFocus=trigger;dialog=root.document.createElement('dialog');var node=dialog;node._createId='arc_'+root.crypto.randomUUID();
    node.className='archive-dialog';node.setAttribute('aria-labelledby','archive-dialog-title');node.innerHTML=shell(row?'나의 독서 기록':'책 등록');root.document.body.appendChild(node);
    node.querySelector('[data-archive-close]').onclick=function(){close();};node.addEventListener('cancel',function(e){e.preventDefault();close();});node.addEventListener('input',function(){node._dirty=true;});
    if(row)showDetail(node,row);else showForm(node,null,{});
    node.showModal();if(root.GrowellPopupHistory)root.GrowellPopupHistory.open('archive',{canClose:canClose,close:function(){if(dialog===node)close(true,true);}});
  }
  function showDetail(node,row){
    var b=row.book;node._dirty=false;
    node.querySelector('.archive-dialog-body').innerHTML='<div class="archive-detail-book">'+cover(b)+'<div><span class="archive-eyebrow">READ & REMEMBER</span><h3>'+esc(b.title)+'</h3><p>'+esc(b.authors.join(' · '))+'</p><p class="archive-detail-publisher">'+esc([b.publisher,b.publishedDate].filter(Boolean).join(' · '))+'</p>'+stars(b.rating)+'</div></div><div class="archive-period"><span>함께한 시간</span><strong>'+esc(period(b))+'</strong></div><section class="archive-reflection"><h3>이 별점을 남긴 이유</h3><p>'+esc(b.review||'아직 남긴 감상이 없어요.')+'</p></section>'+(b.description?'<details class="archive-description"><summary>책 소개</summary><p>'+esc(b.description)+'</p>'+(sourceHref(b)&&b.source!=='yes24'?'<a href="'+esc(sourceHref(b))+'" target="_blank" rel="noopener noreferrer">도서 정보 출처 ↗</a>':'')+'</details>':'')+'<div class="archive-dialog-actions">'+(b.deleted?'<button class="btn btn-primary" data-archive-restore>책장으로 복원</button>':'<button class="btn btn-secondary" data-archive-remove>휴지통으로</button><button class="btn btn-primary" data-archive-edit>기록 수정</button>')+'</div><p class="archive-form-status" role="status"></p>';
    var body=node.querySelector('.archive-dialog-body'),periodNode=body.querySelector('.archive-period');
    periodNode.insertAdjacentHTML('beforebegin','<section class="archive-reading-summary">'+badge(b)+progressHtml(b)+'<p class="archive-time">총 읽은 시간 <strong>'+esc(duration(D().totalReadingSeconds(b)))+'</strong></p>'+(!b.deleted?'<div class="archive-reading-actions"><button class="btn btn-primary" data-archive-timer>'+(b.status==='completed'?'다시 읽기':'타이머로 읽기')+'</button><button class="btn btn-secondary" data-archive-note-add>노트 작성</button></div>':'')+'</section>');
    if(b.tableOfContents)body.querySelector('.archive-dialog-actions').insertAdjacentHTML('beforebegin','<details class="archive-description archive-toc"><summary>목차</summary><p>'+esc(b.tableOfContents)+'</p></details>');
    body.querySelector('.archive-dialog-actions').insertAdjacentHTML('beforebegin',historyHtml(b,row.entry.id));
    body.querySelector('.archive-detail-book').insertAdjacentHTML('afterend',sourceHtml(b)+categoriesHtml(b));
    if(!b.description&&sourceHref(b)&&b.source!=='yes24')body.querySelector('.archive-dialog-actions').insertAdjacentHTML('beforebegin','<p><a href="'+esc(sourceHref(b))+'" target="_blank" rel="noopener noreferrer">도서 정보 보기 ↗</a></p>');
    var edit=node.querySelector('[data-archive-edit]');if(edit)edit.onclick=function(){showForm(node,row,b);};
    var timer=node.querySelector('[data-archive-timer]');if(timer)timer.onclick=function(){openTimer(node,row);};
    var addNote=node.querySelector('[data-archive-note-add]');if(addNote)addNote.onclick=function(){openNote(row,null,function(){updateDetail(node,row.entry.id);});};
    body.querySelectorAll('[data-archive-note-edit]').forEach(function(button){button.onclick=function(){openNote(row,button.dataset.archiveNoteEdit,function(){updateDetail(node,row.entry.id);});};});
    body.querySelectorAll('[data-archive-note-delete]').forEach(function(button){button.onclick=async function(){if(!root.confirm('이 노트를 삭제할까요?'))return;button.disabled=true;try{var latest=await latestRow(row.entry.id);await persist(latest,D().removeNote(latest.book,button.dataset.archiveNoteDelete,Date.now()));await updateDetail(node,row.entry.id);app.render();}catch(e){node.querySelector('.archive-form-status').textContent=e.message;button.disabled=false;}};});
    var remove=node.querySelector('[data-archive-remove]'),restore=node.querySelector('[data-archive-restore]');
    function move(deleted,button){button.disabled=true;app.save(row,Object.assign({},b,{deleted:deleted})).then(function(){if(dialog===node){close(true,true);app.render();}app.toast(deleted?'휴지통으로 옮겼어요. 언제든 복원할 수 있어요.':'책장으로 복원했어요.');}).catch(function(e){if(dialog!==node)return;button.disabled=false;node.querySelector('.archive-form-status').textContent=e.message;});}
    if(remove)remove.onclick=function(){move(true,remove);};if(restore)restore.onclick=function(){move(false,restore);};bindContent(body);
  }
  function historyHtml(b,bookId){
    return '<section class="archive-notes"><h3>나의 기록</h3>'+b.notes.filter(function(n){return !n.deleted;}).slice().sort(function(a,b){return b.createdAt-a.createdAt;}).map(function(n){return '<article><button type="button" class="archive-detail-note" data-archive-read-note="'+esc(n.id)+'" data-archive-note-book="'+esc(bookId)+'"><span class="archive-note-date">'+esc(dateTime(n.createdAt))+'</span>'+(n.title?'<strong>'+esc(n.title)+'</strong>':'')+'<span class="archive-note-preview">'+esc(n.text)+'</span></button>'+(!b.deleted?'<div><button type="button" data-archive-note-edit="'+n.id+'">수정</button><button type="button" data-archive-note-delete="'+n.id+'">삭제</button></div>':'')+'</article>';}).join('')+(!b.notes.some(function(n){return !n.deleted;})?'<p class="archive-form-hint">기억하고 싶은 문장과 생각을 남겨보세요.</p>':'')+'</section><details class="archive-sessions"><summary>읽은 기록 보기 ('+b.readingSessions.length+')</summary>'+b.readingSessions.slice().sort(function(a,b){return b.createdAt-a.createdAt;}).map(function(s){return '<div><span><small>'+esc(dateTime(s.createdAt))+'</small><strong>'+s.startPage+' → '+s.endPage+'쪽</strong></span><span>'+esc(duration(s.seconds))+'</span></div>';}).join('')+'</details>';
  }
  async function updateDetail(node,id){try{var latest=await latestRow(id);if(dialog===node)showDetail(node,latest);}catch(e){if(dialog===node)node.querySelector('.archive-form-status').textContent=e.message;}}
  function openTimer(node,row){var b=row.book;root.GrowellArchiveTimer.open({book:{id:row.entry.id,title:b.title,authors:b.authors,coverUrl:b.coverUrl,source:b.source,sourceUrl:sourceHref(b),pageCount:b.totalPages,currentPage:b.status==='completed'?0:b.currentPage},ownerId:app.session().userId,adapter:{beforeStart:function(ownerId){return app.beforeTimerStart?app.beforeTimerStart(ownerId):true;},getOwnerId:function(){return app.session()&&app.session().userId;},saveSession:async function(id,session,options){var latest=await latestRow(id);if(latest.book.deleted)throw new Error('휴지통의 책은 복원한 뒤 기록해주세요.');if(latest.book.linkedBookId&&app.saveLinkedSession){await app.saveLinkedSession(latest.book.linkedBookId,session,options);signature='';return;}var next=D().addReadingSession(latest.book,session,options);var day=new Date(session.createdAt).toLocaleDateString('sv-SE');if(!next.startDate)next.startDate=day;if(next.status==='completed'&&!next.endDate)next.endDate=day;await persist(latest,next);},openNote:function(book,options){latestRow(book.id).then(function(latest){openNote(latest,null,options&&options.onClose);}).catch(function(e){app.toast(e.message);if(options&&options.onClose)options.onClose();});},onClose:function(){updateDetail(node,row.entry.id);},onSaved:function(){updateDetail(node,row.entry.id);app.render();}}});}
  function registeredGenres(items){return [...new Set(items.flatMap(function(row){return row.book.genres||[];}))].sort(function(a,b){return a.localeCompare(b,'ko');});}
  function categoriesHtml(book){var labels=(book.genres||[]).concat((book.themes||[]).map(function(key){return THEMES[key];}).filter(Boolean));return labels.length?'<span class="archive-book-categories">'+labels.map(function(label){return '<span>'+esc(label)+'</span>';}).join('')+'</span>':'';}
  function sharedNoteRecords(){
    var expected=app.session()&&app.session().userId;if(!expected||app.status()!=='ready'||!app.sharedNotes)return [];
    var supplied;try{supplied=app.sharedNotes();}catch(err){return [];}if(!Array.isArray(supplied))return [];var seen=new Set();
    return supplied.filter(function(note){return note&&note.userId===expected&&typeof note.id==='string'&&THEMES[note.bookId]&&typeof note.text==='string'&&Number.isFinite(note.createdAt);}).map(function(note){
      var key=note.bookId+':'+note.id;if(seen.has(key))return null;seen.add(key);
      var linked=rows.find(function(row){return row.entry.userId===expected&&row.book.linkedBookId===note.bookId;});if(linked&&linked.book.deleted)return null;
      var book=linked?linked.book:{title:note.bookTitle||THEMES[note.bookId]+' 모임 책',authors:[],coverUrl:note.coverUrl||'',genres:Array.isArray(note.genres)?note.genres:[],themes:Array.isArray(note.themes)?note.themes:[note.bookId],notes:[],deleted:false};
      var row=linked||{entry:{id:'shared-note-book:'+note.bookId,userId:expected},book:book};
      return {row:row,note:{id:note.id,title:note.title||'',text:note.text,html:note.html||'',createdAt:note.createdAt},sharedId:note.id,sharedBookId:note.bookId};
    }).filter(Boolean);
  }
  function noteBooks(items){var all=items.filter(function(row){return !row.book.deleted;}).slice(),ids=new Set(all.map(function(row){return row.entry.id;}));sharedNoteRecords().forEach(function(record){if(!ids.has(record.row.entry.id)){all.push(record.row);ids.add(record.row.entry.id);}});return all;}
  function noteRecords(items,theme){
    var result=[],ids=new Set(items.map(function(row){return row.entry.id;}));items.filter(function(row){return !row.book.deleted&&(!theme||(row.book.themes||[]).indexOf(theme)>=0);}).forEach(function(row){row.book.notes.filter(function(note){return !note.deleted;}).forEach(function(note){result.push({row:row,note:note});});});
    sharedNoteRecords().filter(function(record){return ids.has(record.row.entry.id)&&(!theme||(record.row.book.themes||[]).indexOf(theme)>=0);}).forEach(function(record){result.push(record);});return result.sort(function(a,b){return b.note.createdAt-a.note.createdAt;});
  }
  function noteRowsHtml(records){return records.map(function(item){var b=item.row.book,n=item.note,action=item.sharedId?'data-shared-read-note="'+esc(item.sharedId)+'" data-shared-note-book="'+esc(item.sharedBookId)+'"':'data-archive-read-note="'+esc(n.id)+'" data-archive-note-book="'+esc(item.row.entry.id)+'"';return '<article class="archive-note-list-row"><button type="button" '+action+' aria-haspopup="dialog"><span class="archive-note-excerpt"><small>'+esc(dateTime(n.createdAt))+'</small><strong>'+esc(n.title||b.title)+'</strong><span>'+esc(n.text)+'</span><small>'+esc(b.title)+'</small>'+categoriesHtml(b)+'</span>'+cover(b)+'</button>'+sourceHtml(b)+'</article>';}).join('');}
  function notesShelfHtml(all){
    all=noteBooks(all);
    var genres=registeredGenres(all),themes=Object.keys(THEMES).filter(function(key){return all.some(function(row){return (row.book.themes||[]).indexOf(key)>=0;});}),filters=genres.map(function(label){return {key:'genre:'+label,label:label};}).concat(themes.map(function(key){return {key:'theme:'+key,label:THEMES[key]};}));
    if(noteFilter&&!filters.some(function(filter){return filter.key===noteFilter;}))noteFilter='';if(noteBookFilter&&!all.some(function(row){return row.entry.id===noteBookFilter;}))noteBookFilter='';
    var visible=all.filter(function(row){return (!noteBookFilter||row.entry.id===noteBookFilter)&&(!noteFilter||(noteFilter.indexOf('genre:')===0?(row.book.genres||[]).indexOf(noteFilter.slice(6))>=0:(row.book.themes||[]).indexOf(noteFilter.slice(6))>=0));}),records=noteRecords(visible);
    return '<section class="archive-note-shelf"><header><div><span class="archive-eyebrow">WORDS TO KEEP</span><h2>나의 독서 노트 <span>'+records.length+'</span></h2></div>'+(noteBookFilter&&rows.some(function(row){return row.entry.id===noteBookFilter&&!row.book.deleted;})?'<button type="button" class="btn btn-secondary" data-archive-note-selected-add>노트 쓰기</button>':'')+'</header><div class="archive-note-controls"><label><span class="sr-only">책별 노트</span><select data-note-book-filter aria-label="책별 노트"><option value="">모든 책</option>'+all.map(function(row){return '<option value="'+esc(row.entry.id)+'"'+(noteBookFilter===row.entry.id?' selected':'')+'>'+esc(row.book.title)+'</option>';}).join('')+'</select></label><div class="archive-note-filter-tabs" aria-label="노트 분류"><button type="button" data-note-filter="" aria-pressed="'+!noteFilter+'">전체</button>'+filters.map(function(filter){return '<button type="button" data-note-filter="'+esc(filter.key)+'" aria-pressed="'+(noteFilter===filter.key)+'">'+esc(filter.label)+'</button>';}).join('')+'</div></div><div class="archive-note-list">'+(records.length?noteRowsHtml(records):'<p class="archive-form-hint">'+(all.length?'책을 선택하고 기억하고 싶은 문장과 생각을 남겨보세요.':'책장에 책을 담으면 독서 노트를 함께 모아볼 수 있어요.')+'</p>')+'</div></section>';
  }
  function richNoteHtml(note){return note.html&&app.sanitizeHtml?app.sanitizeHtml(note.html):'<p>'+esc(note.text).replace(/\n/g,'<br>')+'</p>';}
  function closeNote(){if(!noteDialog)return;var n=noteDialog;noteDialog=null;if(n._editorCleanup)n._editorCleanup();n.close();n.remove();if(root.GrowellPopupHistory)root.GrowellPopupHistory.closed('archive-note');if(n._returnFocus&&n._returnFocus.isConnected)n._returnFocus.focus({preventScroll:true});if(n._onClose)n._onClose();}
  function openNote(row,id,onClose,readOnly,trigger){
    var expected=app.session()&&app.session().userId;if(!expected||row.entry.userId!==expected||(row.book.deleted&&!readOnly))return;
    closeNote();var old=id?row.book.notes.find(function(note){return note.id===id&&!note.deleted;}):null;if(id&&!old)return;
    var noteId=old?old.id:'note_'+root.crypto.randomUUID(),created=old?old.createdAt:Date.now();
    var n=root.document.createElement('dialog');noteDialog=n;n._onClose=onClose;n._returnFocus=trigger;n.className='archive-dialog archive-note-dialog';n.setAttribute('aria-label','독서 노트');
    n.innerHTML='<header class="archive-dialog-head"><h2>'+esc(row.book.title)+'</h2><button type="button" class="icon-btn" data-note-close aria-label="노트 닫기">'+icon('close')+'</button></header><div class="archive-note-content"></div>';root.document.body.appendChild(n);
    function active(){return noteDialog===n&&app.session()&&app.session().userId===expected&&app.status()==='ready';}
    function canCloseNote(){return !n._busy&&(!n._dirty||root.confirm('작성 중인 노트를 저장하지 않고 닫을까요?'));}
    function changed(){n._dirty=true;}
    n.querySelector('[data-note-close]').onclick=function(){if(canCloseNote())closeNote();};n.addEventListener('cancel',function(e){e.preventDefault();if(canCloseNote())closeNote();});n.addEventListener('input',changed);
    function cleanup(){if(n._editorCleanup){n._editorCleanup();n._editorCleanup=null;}}
    function view(){
      cleanup();n._dirty=false;n.querySelector('.archive-note-content').innerHTML='<div class="archive-dialog-body"><span class="archive-note-date">'+esc(dateTime(old.createdAt))+'</span>'+(old.title?'<h3 class="archive-note-title">'+esc(old.title)+'</h3>':'')+categoriesHtml(row.book)+'<div class="archive-note-rich">'+richNoteHtml(old)+'</div>'+sourceHtml(row.book)+'<p class="archive-form-status" role="status"></p>'+(!row.book.deleted?'<div class="archive-dialog-actions"><button type="button" class="btn btn-secondary" data-note-delete>삭제</button><button type="button" class="btn btn-primary" data-note-edit>수정</button></div>':'')+'</div>';
      if(row.book.deleted)return;n.querySelector('[data-note-edit]').onclick=edit;n.querySelector('[data-note-delete]').onclick=async function(){if(!active()||n._busy||!root.confirm('이 노트를 삭제할까요?'))return;n._busy=true;var button=this;button.disabled=true;try{var latest=await latestRow(row.entry.id);if(!active())return;var current=latest.book.notes.find(function(note){return note.id===noteId;});if(JSON.stringify(current)!==JSON.stringify(old))throw new Error('다른 곳에서 수정된 노트예요. 다시 열어주세요.');await persist(latest,D().removeNote(latest.book,noteId,Date.now()));if(active()){closeNote();app.render();}}catch(err){if(active())n.querySelector('.archive-form-status').textContent=err.message;}finally{n._busy=false;button.disabled=false;}};
    }
    function edit(){
      if(!active()||n._busy)return;cleanup();n._dirty=false;var useRich=!!(app.editorHtml&&app.bindEditor&&app.sanitizeHtml&&app.plainText),initialHtml=old?richNoteHtml(old):'';
      n.querySelector('.archive-note-content').innerHTML='<form id="archive-note-form" class="archive-dialog-body">'+field('제목 (선택)','noteTitle',old&&old.title)+'<label class="archive-field">나의 기록</label>'+(useRich?'<div class="archive-rich-editor">'+app.editorHtml(initialHtml)+'</div>':'<label class="archive-field"><span class="sr-only">나의 기록</span><textarea name="text" rows="7" maxlength="10000" required placeholder="책 속 문장과 나의 생각을 남겨주세요.">'+esc(old?old.text:'')+'</textarea></label>')+'<p class="archive-form-status" role="status"></p><div class="archive-dialog-actions">'+(old&&readOnly?'<button type="button" class="btn btn-secondary" data-note-view>돌아가기</button>':'')+'<button type="submit" class="btn btn-primary" data-archive-note-save>노트 저장</button></div></form>';
      var form=n.querySelector('form');form.elements.noteTitle.maxLength=300;
      if(useRich)n._editorCleanup=app.bindEditor(form.querySelector('.archive-rich-editor'),changed);
      var back=form.querySelector('[data-note-view]');if(back)back.onclick=function(){if(canCloseNote())view();};
      form.onsubmit=async function(e){e.preventDefault();var button=form.querySelector('[type="submit"]');if(!active()||button.disabled)return;button.disabled=true;n._busy=true;try{
        var html=useRich?app.sanitizeHtml(form.querySelector('[contenteditable="true"]').innerHTML):'',text=useRich?app.plainText(html):form.elements.text.value;
        var latest=await latestRow(row.entry.id);if(!active())return;if(latest.book.deleted)throw new Error('책을 복원한 뒤 노트를 작성해주세요.');if(old){var current=latest.book.notes.find(function(item){return item.id===id;});if(JSON.stringify(current)!==JSON.stringify(old))throw new Error('다른 곳에서 수정된 노트예요. 다시 열어주세요.');}
        var next=D().upsertNote(latest.book,{id:noteId,title:form.elements.noteTitle.value,text:text,html:html,createdAt:created,updatedAt:old?Date.now():null});await persist(latest,next);if(active()){n._dirty=false;closeNote();app.render();}
      }catch(err){if(active())form.querySelector('.archive-form-status').textContent=err.message;}finally{n._busy=false;button.disabled=false;}};
    }
    if(readOnly&&old)view();else edit();n.showModal();if(root.GrowellPopupHistory)root.GrowellPopupHistory.open('archive-note',{canClose:canCloseNote,close:closeNote});
  }
  function reflectionHtml(theme){
    if(!app||!app.session())return '';ensure();if(app.status()!=='ready'||!rows._loaded||error)return '';if(theme&&!THEMES[theme])return '';
    var records=noteRecords(noteBooks(rows),theme),title=theme?THEMES[theme]+'에 대한 고찰':'아카이브 기록';
    return '<section class="archive-records archive-reflections"><header><h3>'+title+' <span>'+records.length+'</span></h3><a href="#/archive">책장 보기 →</a></header><div class="archive-note-list">'+(records.length?noteRowsHtml(records):'<p class="archive-form-hint">'+(theme?THEMES[theme]+' 주제의 책에서 남긴 노트가 여기에 모여요.':'아카이브의 독서 노트를 여기에서도 볼 수 있어요.')+'</p>')+'</div></section>';
  }
  function recordsHtml(theme){return reflectionHtml(theme);}
  function field(label,key,value,type){return '<label class="archive-field">'+label+'<input name="'+key+'" type="'+(type||'text')+'" value="'+esc(value||'')+'"'+(key==='title'?' required maxlength="300"':'')+'></label>';}
  function showForm(node,row,initial){
    var b=Object.assign({authors:[],rating:0,status:'unread',currentPage:0,genres:[],themes:[],genreSource:''},initial),selected=b,genreEdited=false,themesEdited=false;
    node.querySelector('.archive-dialog-body').innerHTML=(row?'':searchPanelHtml())+
      '<form id="archive-form"><div class="archive-form-book"><div><div id="archive-cover-preview">'+cover(b)+'</div><label class="archive-upload">표지 사진 선택<input type="file" accept="image/jpeg,image/png,image/webp" name="coverFile"></label></div><div>'+field('책 제목','title',b.title)+field('저자','authors',(b.authors||[]).join(', '))+field('출판사','publisher',b.publisher)+'</div></div><div class="archive-date-fields">'+field('읽기 시작한 날','startDate',b.startDate,'date')+field('다 읽은 날','endDate',b.endDate,'date')+'</div><p class="archive-form-hint">정확한 날짜가 기억나지 않으면 비워두어도 좋아요.</p><fieldset class="archive-rating"><legend>나의 별점</legend><div>'+[1,2,3,4,5].map(function(n){return '<label title="'+n+'점"><input type="radio" name="rating" value="'+n+'"'+(b.rating===n?' checked':'')+'><span aria-hidden="true">★</span><span class="sr-only">'+n+'점</span></label>';}).join('')+'<button type="button" data-clear-rating>초기화</button></div></fieldset><label class="archive-field">이 별점을 남긴 이유<textarea name="review" rows="4" maxlength="10000" placeholder="좋았던 점, 아쉬웠던 점, 오래 기억하고 싶은 생각을 남겨주세요.">'+esc(b.review||'')+'</textarea></label><details class="archive-description"><summary>책 소개 수정</summary><label class="archive-field"><span class="sr-only">책 소개</span><textarea name="description" rows="4" maxlength="16000">'+esc(b.description||'')+'</textarea></label></details><p class="archive-form-status" role="status"></p><div class="archive-dialog-actions">'+(row?'<button type="button" class="btn btn-secondary" data-archive-cancel-edit>돌아가기</button>':'')+'<button type="submit" class="btn btn-primary">'+(row?'수정 저장':'책장에 담기')+'</button></div></form>';
    var form=node.querySelector('#archive-form'),status=form.querySelector('.archive-form-status');
    node._bookDraftDirty=false;form.addEventListener('input',function(){node._bookDraftDirty=true;});form.addEventListener('change',function(){node._bookDraftDirty=true;});
    form.querySelector('.archive-form-book').insertAdjacentHTML('afterend','<div class="archive-selected-source">'+sourceHtml(b)+'</div>');
    form.querySelector('.archive-date-fields').insertAdjacentHTML('beforebegin','<section class="archive-classification"><label class="archive-field">책 장르<input name="genres" value="'+esc((b.genres||[]).join(', '))+'" maxlength="650" placeholder="예: 인문, 에세이"></label><div class="archive-genre-help"><p class="archive-form-hint" data-genre-status>도서 분류가 있으면 자동으로 채워져요. 여러 장르는 쉼표로 구분해주세요.</p><button type="button" data-fetch-genres>분류 가져오기</button></div><fieldset class="archive-theme-fields"><legend>함께 생각할 주제 <span>여러 개 선택 가능</span></legend><div>'+Object.keys(THEMES).map(function(key){return '<label><input type="checkbox" name="theme" value="'+key+'"'+((b.themes||[]).indexOf(key)>=0?' checked':'')+'>'+THEMES[key]+'</label>';}).join('')+'</div><p class="archive-form-hint">선택한 주제의 나의 공간에도 이 책의 노트가 모여요.</p></fieldset></section>');
    form.elements.genres.oninput=function(){genreEdited=true;selected.genreSource='manual';node._bookDraftDirty=true;node._genreVersion=(node._genreVersion||0)+1;if(node._genreAbort)node._genreAbort.abort();node._genrePending=false;node._genrePromise=null;form.querySelector('[data-genre-status]').textContent='내가 정한 장르로 저장해요.';};
    form.querySelectorAll('[name="theme"]').forEach(function(input){input.onchange=function(){themesEdited=true;node._dirty=true;node._bookDraftDirty=true;};});
    function fetchGenres(){
      if(form.querySelector('[type="submit"]').disabled)return;
      var href=sourceHref(selected),button=form.querySelector('[data-fetch-genres]');button.hidden=selected.source!=='yes24'||!href;if(button.hidden)return;
      if(node._genreAbort)node._genreAbort.abort();var control=new AbortController(),version=(node._genreVersion||0)+1,expectedOwner=app.session()&&app.session().userId,snapshot=form.elements.genres.value,titleSnapshot=form.elements.title.value,authorSnapshot=form.elements.authors.value;node._genreAbort=control;node._genreVersion=version;
      var hint=form.querySelector('[data-genre-status]');hint.textContent='도서 분류를 불러오는 중이에요.';node._genrePending=true;
      node._genrePromise=fetch('/api/book-search?mode=genres&q='+encodeURIComponent(href),{signal:control.signal}).then(function(response){return response.json();}).then(function(result){
        if(dialog!==node||!form.isConnected||node._genreVersion!==version||!app.session()||app.session().userId!==expectedOwner||sourceHref(selected)!==href||form.elements.title.value!==titleSnapshot||form.elements.authors.value!==authorSnapshot||form.elements.genres.value!==snapshot||(form.querySelector('[type="submit"]').disabled&&!node._waitingForGenre))return;
        var genres=Array.isArray(result.genres)?result.genres.filter(function(value){return typeof value==='string';}).slice(0,8):[];
        if(genres.length){form.elements.genres.value=genres.join(', ');selected.genreSource=result.genreSource==='google'?'google':'yes24';hint.textContent='도서 분류를 가져왔어요. 필요하면 직접 바꿀 수 있어요.';node._dirty=true;}else hint.textContent='제공된 장르가 없어요. 원하면 직접 입력해주세요.';
      }).catch(function(err){if(err.name==='AbortError')return;if(dialog===node&&node._genreVersion===version)hint.textContent='분류를 불러오지 못했어요. 직접 입력하거나 비워두어도 좋아요.';}).finally(function(){if(node._genreVersion===version)node._genrePending=false;});
    }
    var fetchGenreButton=form.querySelector('[data-fetch-genres]');fetchGenreButton.hidden=b.source!=='yes24'||!sourceHref(b);fetchGenreButton.onclick=fetchGenres;
    form.querySelector('.archive-date-fields').insertAdjacentHTML('beforebegin','<fieldset class="archive-status-fields"><legend>독서 상태</legend><div>'+[['unread','읽기 전'],['reading','읽는 중'],['completed','완독']].map(function(pair){return '<label><input type="radio" name="status" value="'+pair[0]+'"'+(b.status===pair[0]?' checked':'')+'>'+pair[1]+'</label>';}).join('')+'</div></fieldset><div class="archive-page-fields">'+field('현재 읽은 쪽수','currentPage',String(b.currentPage||0),'number')+field('전체 쪽수','totalPages',b.totalPages||b.pageCount||'','number')+'</div>');
    form.elements.currentPage.min='0';form.elements.currentPage.max='100000';form.elements.totalPages.min='1';form.elements.totalPages.max='100000';
    function stateChanged(){var value=selected.linkedBookId?selected.status:new FormData(form).get('status');form.elements.currentPage.disabled=value!=='reading';if(value==='unread')form.elements.currentPage.value='0';if(value==='completed'&&form.elements.totalPages.value)form.elements.currentPage.value=form.elements.totalPages.value;form.elements.endDate.disabled=value!=='completed';}
    form.querySelectorAll('[name="status"]').forEach(function(radio){radio.onchange=stateChanged;});form.elements.totalPages.oninput=stateChanged;
    form.querySelector('.archive-page-fields').insertAdjacentHTML('afterend','<p class="archive-form-hint archive-linked-hint" hidden>모임 책의 상태와 읽은 쪽수는 독서 타이머 기록과 함께 반영돼요.</p>');
    function syncLinkedFields(){var linked=!!selected.linkedBookId;form.querySelectorAll('[name="status"]').forEach(function(radio){radio.disabled=linked;if(linked)radio.checked=radio.value===selected.status;});form.elements.currentPage.readOnly=linked;form.elements.totalPages.readOnly=linked;form.querySelector('.archive-linked-hint').hidden=!linked;if(linked){form.elements.currentPage.value=selected.currentPage||0;form.elements.totalPages.value=selected.totalPages||selected.pageCount||'';}stateChanged();}syncLinkedFields();
    function ratingPaint(){var value=Number(new FormData(form).get('rating')||0);form.querySelectorAll('.archive-rating label').forEach(function(label){label.classList.toggle('is-rated',Number(label.querySelector('input').value)<=value);});}ratingPaint();
    form.querySelectorAll('[name="rating"]').forEach(function(r){r.onchange=ratingPaint;});form.querySelector('[data-clear-rating]').onclick=function(){form.querySelectorAll('[name="rating"]').forEach(function(r){r.checked=false;});node._dirty=true;ratingPaint();};
    var cancel=form.querySelector('[data-archive-cancel-edit]');if(cancel)cancel.onclick=function(){if(canClose())showDetail(node,row);};
    form.elements.coverFile.onchange=async function(){var file=form.elements.coverFile.files[0];if(!file)return;var version=(node._coverVersion||0)+1;node._coverVersion=version;node._coverLoading=true;try{var result=await readCover(file);if(dialog!==node||node._coverVersion!==version)return;selected.coverUrl=result;node.querySelector('#archive-cover-preview').innerHTML=cover(Object.assign({},selected,{title:form.elements.title.value}));status.textContent='';}catch(e){if(dialog===node&&node._coverVersion===version)status.textContent=e.message;}finally{if(node._coverVersion===version)node._coverLoading=false;}};
    form.onsubmit=async function(event){
      event.preventDefault();var button=form.querySelector('[type="submit"]');if(button.disabled||dialog!==node)return;if(node._coverLoading){status.textContent='표지 사진을 준비하고 있어요. 잠시 후 저장해주세요.';return;}
      var saveSession=app.session(),saveOwner=saveSession&&saveSession.userId,saveMaterial=saveSession&&saveSession.keyB64;if(!saveOwner)return;button.disabled=true;
      try{
        if(node._genrePending&&node._genrePromise){
          status.textContent='도서 분류를 확인하고 있어요…';node._waitingForGenre=true;var timeoutId;
          try{await Promise.race([node._genrePromise,new Promise(function(resolve){timeoutId=root.setTimeout(resolve,4000);})]);}
          finally{root.clearTimeout(timeoutId);node._waitingForGenre=false;}
          if(node._genrePending){node._genreVersion=(node._genreVersion||0)+1;if(node._genreAbort)node._genreAbort.abort();node._genrePending=false;node._genrePromise=null;form.querySelector('[data-genre-status]').textContent='분류 조회가 지연되어 입력한 장르로 저장해요. 장르는 나중에 바꿀 수 있어요.';}
        }
        if(dialog!==node||app.session()!==saveSession||saveSession.userId!==saveOwner||saveSession.keyB64!==saveMaterial||app.status()!=='ready')return;
        if(node._coverLoading)throw new Error('표지 사진을 준비하고 있어요. 잠시 후 저장해주세요.');status.textContent='저장 중…';
        var data=new FormData(form),book=Object.assign({},selected,{title:data.get('title'),authors:String(data.get('authors')||'').split(',').map(function(a){return a.trim();}).filter(Boolean),publisher:data.get('publisher'),startDate:data.get('startDate'),endDate:data.get('endDate'),rating:Number(data.get('rating')||0),review:data.get('review'),description:data.get('description'),genres:String(data.get('genres')||'').split(',').map(function(value){return value.trim();}).filter(Boolean),themes:form.querySelectorAll('[name="theme"]:checked').length?Array.from(form.querySelectorAll('[name="theme"]:checked')).map(function(input){return input.value;}):[],status:selected.linkedBookId?selected.status:data.get('status'),currentPage:Number(form.elements.currentPage.value||0),totalPages:data.get('totalPages')||null});
        D().prepare(book);await persist(row,book,node._createId);if(dialog===node){close(true,true);app.render();}if(app.session()&&app.session().userId===saveOwner)app.toast('나의 책장에 저장했어요.');
      }catch(e){if(dialog===node)status.textContent=e.message||'저장하지 못했어요. 다시 시도해주세요.';}finally{node._waitingForGenre=false;button.disabled=false;}
    };
    bindBookSearch(node,function(item){
      if(node._coverLoading||form.querySelector('[type="submit"]').disabled)return false;
      if(node._genreAbort)node._genreAbort.abort();node._genrePending=false;node._genrePromise=null;node._genreVersion=(node._genreVersion||0)+1;
      var wasLinked=!!selected.linkedBookId,linkedRow=item.linkedBookId&&rows.find(function(saved){return saved.book.linkedBookId===item.linkedBookId;});
      if(linkedRow){if(node._bookDraftDirty&&!root.confirm('작성 중인 책 정보가 있어요. 저장하지 않고 책장에 있는 모임 책을 열까요?'))return false;showDetail(node,linkedRow);app.toast(linkedRow.book.deleted?'휴지통에 있는 모임 책이에요. 복원해서 이어서 기록할 수 있어요.':'이미 책장에 있는 모임 책이에요.');return true;}
      selected=Object.assign({},selected,{publishedDate:'',isbn:'',source:'',sourceUrl:'',coverUrl:'',description:'',tableOfContents:'',pageCount:null,totalPages:null,linkedBookId:'',status:'unread',currentPage:0},item,{providerId:item.providerId||item.id||'',deleted:false});
      if(wasLinked&&!selected.linkedBookId){form.querySelectorAll('[name="status"]').forEach(function(radio){radio.checked=radio.value==='unread';});form.elements.currentPage.value='0';}
      form.elements.totalPages.value=item.totalPages||item.pageCount||'';syncLinkedFields();form.elements.title.value=item.title;form.elements.authors.value=item.authors.join(', ');form.elements.publisher.value=item.publisher||'';form.elements.description.value=item.description||'';
      if(!themesEdited)form.querySelectorAll('[name="theme"]').forEach(function(input){input.checked=(item.themes||[]).indexOf(input.value)>=0;});
      if(!genreEdited){form.elements.genres.value=(item.genres||[]).join(', ');selected.genreSource=item.genreSource||'';}else selected.genreSource='manual';
      fetchGenreButton.hidden=selected.source!=='yes24'||!sourceHref(selected);form.querySelector('[data-genre-status]').textContent=genreEdited?'내가 정한 장르로 저장해요.':form.elements.genres.value?'도서 분류를 가져왔어요. 필요하면 직접 바꿀 수 있어요.':'제공된 장르가 없으면 직접 입력할 수 있어요.';if(!genreEdited&&!form.elements.genres.value&&!fetchGenreButton.hidden)fetchGenres();
      node.querySelector('#archive-cover-preview').innerHTML=cover(selected);node.querySelector('.archive-selected-source').innerHTML=sourceHtml(selected);node._dirty=true;bindImages(node);form.elements.title.focus({preventScroll:true});return true;
    });
    bindImages(node);
  }
  function searchPanelHtml(){
    return '<section class="archive-book-search"><h3>어떤 책을 담을까요?</h3><div class="archive-search-tabs" aria-label="책 찾는 방법">'+[['search','책 검색'],['link','링크로 등록'],['new','신간']].map(function(pair){return '<button type="button" data-book-search-mode="'+pair[0]+'" aria-pressed="'+(pair[0]==='search')+'">'+pair[1]+'</button>';}).join('')+'</div><form id="archive-search-form"><div class="archive-search-query"><label class="archive-filter-search">'+icon('search')+'<input name="query" aria-label="등록할 책 검색" placeholder="책 제목 · 저자 · ISBN" minlength="2" maxlength="120" required></label><button class="btn btn-secondary" type="submit">검색</button></div><div class="archive-search-options"><label>검색 범위<select name="scope" aria-label="도서 검색 범위"><option value="domestic">국내도서</option><option value="foreign">외국도서</option></select></label><label>정렬<select name="sort" aria-label="도서 검색 정렬"><option value="relevance">관련도순</option><option value="recent">최신순</option></select></label></div></form><p class="archive-search-note" role="status">국내도서를 먼저 찾아요. 책을 선택하면 표지와 기본 정보가 채워져요.</p><div class="archive-search-results"></div><button type="button" class="archive-search-more" hidden>더 보기</button></section>';
  }
  function bindBookSearch(node,onSelect){
    var form=node.querySelector('#archive-search-form');if(!form)return;
    var note=node.querySelector('.archive-search-note'),results=node.querySelector('.archive-search-results'),more=node.querySelector('.archive-search-more');
    var mode='search',queries={search:'',link:''},found=[],page=0,hasMore=false,requestKey='',searchOwner=app.session()&&app.session().userId;
    function active(){return dialog===node&&form.isConnected&&app.session()&&app.session().userId===searchOwner&&app.status()==='ready';}
    function invalidate(){if(node._searchAbort)node._searchAbort.abort();node._searchAbort=null;form.querySelector('[type="submit"]').disabled=false;more.disabled=false;results.setAttribute('aria-busy','false');}
    function unique(items){var ids=new Set(),titles=new Set();return items.filter(function(book){var id=String(book.isbn||'').replace(/[^0-9X]/gi,''),title=String(book.title||'').trim().toLowerCase();if(!title||(id&&ids.has(id))||titles.has(title))return false;if(id)ids.add(id);titles.add(title);return true;});}
    function paint(message){
      note.textContent=message||(found.length?'등록할 책을 선택해주세요.':'검색 결과가 없어요. 제목이나 ISBN을 바꾸거나 아래에서 직접 등록해주세요.');
      results.innerHTML=found.map(function(book,i){return '<article class="archive-search-result"><button type="button" data-search-result="'+i+'">'+cover(book)+'<span><strong>'+esc(book.title)+'</strong><small>'+esc(book.authors.join(' · '))+'</small><small>'+esc([book.publisher,book.publishedDate].filter(Boolean).join(' · '))+'</small></span></button>'+(book._localCatalog?'<span class="archive-source">모임 도서</span>':sourceHtml(book))+'</article>';}).join('');
      results.querySelectorAll('[data-search-result]').forEach(function(button){button.onclick=function(){if(!active()||!onSelect(found[Number(button.dataset.searchResult)]))return;invalidate();found=[];results.innerHTML='';more.hidden=true;note.textContent='책 정보를 가져왔어요. 독서 상태와 나의 기록을 이어서 남겨주세요.';};});more.hidden=!hasMore;bindImages(results);
    }
    async function load(append){
      if(!active())return;var query=mode==='new'?'':form.elements.query.value.trim();if(mode!=='new'&&query.length<2){note.textContent=mode==='link'?'YES24 책 주소 또는 ISBN 13자리를 입력해주세요.':'검색어를 두 글자 이상 입력해주세요.';return;}
      var scope=mode==='new'?'domestic':form.elements.scope.value,sort=mode==='new'?'recent':form.elements.sort.value;
      var key=[mode,scope,sort,query].join('|');if(append&&key!==requestKey)append=false;var nextPage=append?page+1:1;if(nextPage>50)return;
      invalidate();var control=new AbortController();node._searchAbort=control;requestKey=key;form.querySelector('[type="submit"]').disabled=true;more.disabled=true;results.setAttribute('aria-busy','true');note.textContent=mode==='new'?'새로 나온 책을 불러오는 중이에요…':'책을 찾는 중이에요…';
      if(!append){found=[];page=0;hasMore=false;results.innerHTML='';more.hidden=true;}
      var local=mode==='search'&&scope==='domestic'&&nextPage===1?app.catalog().filter(function(book){return (book.title+' '+book.authors.join(' ')+' '+(book.isbn||'')).toLowerCase().includes(query.toLowerCase());}).map(function(book){return Object.assign({},book,{_localCatalog:true});}):[];
      function current(){return active()&&node._searchAbort===control;}
      try{
        var response=await fetch('/api/book-search?mode='+mode+'&scope='+scope+'&sort='+sort+'&page='+nextPage+'&q='+encodeURIComponent(query),{signal:control.signal});var remote=await response.json();if(!current())return;
        var items=response.ok===false?[]:(Array.isArray(remote.items)?remote.items:[]).filter(function(item){return item&&typeof item.title==='string'&&Array.isArray(item.authors);}).map(function(item){return Object.assign({},item,{coverUrl:item.thumbnail||item.coverUrl||'',providerId:item.id||item.providerId||''});});
        found=unique((append?found:[]).concat(items,local));page=nextPage;hasMore=response.ok!==false&&remote.hasMore===true&&page<50;
        paint(remote.error?(remote.error+(local.length?' 아래 모임 도서는 바로 등록할 수 있어요.':'')):response.ok===false?'검색 연결이 원활하지 않아요. 아래에서 직접 등록할 수 있어요.':'');
      }catch(e){if(e.name==='AbortError'||!current())return;found=unique((append?found:[]).concat(local));hasMore=false;paint('검색 연결이 원활하지 않아요. '+(local.length?'아래 모임 도서를 선택하거나 직접 등록할 수 있어요.':'아래에서 직접 등록할 수 있어요.'));}
      finally{if(current()){form.querySelector('[type="submit"]').disabled=false;more.disabled=false;results.setAttribute('aria-busy','false');}}
    }
    form.onsubmit=function(event){event.preventDefault();return load(false);};more.onclick=function(){if(!more.disabled&&hasMore)return load(true);};
    form.elements.query.oninput=function(){invalidate();found=[];page=0;hasMore=false;results.innerHTML='';more.hidden=true;};
    node.querySelectorAll('[data-book-search-mode]').forEach(function(button){button.onclick=function(){var next=button.dataset.bookSearchMode;if(mode===next)return;if(mode!=='new')queries[mode]=form.elements.query.value;invalidate();mode=next;found=[];page=0;hasMore=false;results.innerHTML='';more.hidden=true;
      node.querySelectorAll('[data-book-search-mode]').forEach(function(tab){tab.setAttribute('aria-pressed',String(tab===button));});
      form.querySelector('.archive-search-query').hidden=mode==='new';form.querySelector('.archive-search-options').hidden=mode!=='search';form.elements.query.disabled=mode==='new';form.elements.query.required=mode!=='new';form.elements.query.maxLength=mode==='link'?2048:120;form.elements.query.value=queries[mode]||'';form.elements.query.placeholder=mode==='link'?'YES24 책 주소 또는 ISBN 13자리':'책 제목 · 저자 · ISBN';form.elements.query.setAttribute('aria-label',mode==='link'?'YES24 책 주소 또는 ISBN':'등록할 책 검색');form.querySelector('[type="submit"]').textContent=mode==='link'?'가져오기':'검색';
      note.textContent=mode==='link'?'YES24에서 찾은 책의 주소를 붙여넣어 주세요. ISBN으로도 찾을 수 있어요.':'국내도서를 먼저 찾아요. 책을 선택하면 표지와 기본 정보가 채워져요.';if(mode==='new')return load(false);form.elements.query.focus({preventScroll:true});};});
    [form.elements.scope,form.elements.sort].forEach(function(select){select.onchange=function(){invalidate();found=[];results.innerHTML='';more.hidden=true;if(form.elements.query.value.trim().length>=2)return load(false);};});
  }
  function readCover(file){return new Promise(function(resolve,reject){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>5*1024*1024){reject(new Error('5MB 이하의 JPG, PNG, WebP 사진을 선택해주세요.'));return;}var url=URL.createObjectURL(file),img=new Image();img.onload=function(){try{var scale=Math.min(1,600/Math.max(img.width,img.height)),canvas=root.document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));var ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',0.82));}catch(e){reject(new Error('사진을 읽지 못했어요. 다른 사진을 선택해주세요.'));}finally{URL.revokeObjectURL(url);}};img.onerror=function(){URL.revokeObjectURL(url);reject(new Error('사진을 읽지 못했어요.'));};img.src=url;});}
  root.addEventListener('hashchange',function(){closeNote();close(false,true);});
  root.GrowellArchive={configure:configure,html:html,recordsHtml:recordsHtml,reflectionHtml:reflectionHtml,bind:bind,reset:reset};
})(window);
